name = "meta-ads-dashboard"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "meta-dash-db"
database_id = "51148488-b820-48e3-badc-885a696b6c9b"
